name: Bug Report — General
description: Report a bug with CodeVolt website, newsletter, or other services
title: "[BUG] "
labels: ["bug", "general", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Use this form for:
        - CodeVolt website issues
        - Newsletter problems
        - General service issues
        
        For PriceVolt-specific bugs, please use the PriceVolt bug report template.

  - type: dropdown
    id: service
    attributes:
      label: Affected Service
      description: Which service has the issue?
      options:
        - CodeVolt website (codevolt.co.uk)
        - Newsletter subscription
        - Privacy/Data Request
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: What happened? What did you expect to happen?
      placeholder: |
        Clear description of the issue:
        - What were you trying to do?
        - What actually happened?
        - What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser / Device
      description: What browser and device were you using?
      placeholder: e.g., Chrome 120 on macOS, Safari iOS, etc.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots
      placeholder: Paste screenshots here

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
